### ISSUE TITLE
VPSearch Paper and Package Reviewer Comments

### ISSUE THREAD

**Issue by tamarahadz** [enthought/vpsearch#20]
- [x] **Contribution and authorship:** Submitting author has made the most major contributions to the software, however the [#2 most frequent contributor](https://github.com/enthought/vpsearch/graphs/contributors) (@peterzahemszky) is not mentioned in the paper

- [x] **Community guidelines:** Add community guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support in README of repo

- [x] **References:** [DIAMOND](https://www.nature.com/articles/s41592-021-01101-x) software mentioned in paper in line 41 but not cited

- [x] **Functionality:** For the RDP data used in the example (rdp_download_281261seqs_dedup.fa), please provide a link to where users can download the data. For the example query (query.fa), provide the example in the GitHub repo or a link to where this sequence is from. This will aid users in testing the package on their own after installation. In testing I tried using the [16S Bacteria Aligned FASTA](https://rdp.cme.msu.edu/misc/resources.jsp) but was unsure whether this is the dataset you used or not.

- [x] **Performance:** I installed the package following the Docker instructions on the README. Running the package in the docker image led to memory issues. Can you recommend the amount of memory needed to run your example before I continue testing?

**Comment by jvkersch** [comment]
@tamarahadz Thank you for taking the application for a spin, and for your insightful feedback! I think we can address all of your points in short order, but I will admit that the Docker issue has us a bit stumped. Could you tell us what platform you are running Docker on, and what amount of memory you have available?

**Comment by jvkersch** [comment]
Taking another look at README, I realize that the installation instructions are outdated: the package is pip installable and this is probably the easiest way to go. This should be addressed as well while we're at it.

- [ ] Update README to mention pip install (#23).

**Comment by tamarahadz** [comment]
We are running Docker on Ubuntu 18 and have 32GB of memory availible.

**Comment by jvkersch** [comment]
@tamarahadz Thanks for letting me know, and I'm sorry for your trouble -- we should have made the dataset more clear!

Looking at your original description, I think the issue with memory exhaustion is because of the size of the input file that you used, which contains RDP sequences with gaps. In particular, since vpsearch has to do quite a few Needleman-Wunsch alignments, it is not so much the number of sequences that matters but the length of the typical sequence. For sequence files that contain just 16S genes (i.e. 1500 bp sequences) the total amount of memory used and the time needed to construct the index should be manageable. For example, for 100,000 sequences from the Silva database, memory usage is 500 MB or so (both when running natively and inside the Docker container).

In response to your comment, we've done the following so far (note that most of these changes are in open PRs):

1. Provided a sample dataset and updated the README to make it more clear on how to get started with vpsearch (#21)
2. Uploaded that same dataset to [Zenodo](https://zenodo.org/record/6509511), for easy retrievability.
2. Updated the installation instructions to emphasize the wheel-based install (#25)

I expect these will land in the repo in the next few days or so. If you want to give vpsearch another spin in the meantime, your could install it on your Linux machine via `python -m pip install vpsearch`, and run it on the data provided in https://zenodo.org/record/6509511.

**Comment by jvkersch** [comment]
@tamarahadz A quick interim update regarding your first item: Peter didn't want to be named as an author on the paper, so we chose to include his contribution in the acknowledgements instead.

**Comment by jvkersch** [comment]
@tamarahadz I'm glad to say that we addressed the last task on the list over the weekend. I will leave this issue open so that you can have another look -- please let us know if there is anything else we could do, or if any of your suggestions were not addressed adequately.

**Comment by jvkersch** [comment]
@tamarahadz I will close this issue as finished, but don't hesitate to re-open or create additional issues if anything else arises.
